language: java

sudo: false

cache:
  directories:
    - "$HOME/.m2"

jdk:
  - openjdk8

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - export PROJECT_VERSION=$(mvn help:evaluate -N -Dexpression=project.version -q -DforceStdout)

install:
  - mvn --settings .travis/maven.xml -Prelease install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script:
  - mvn --settings .travis/maven.xml -Prelease clean deploy

deploy:
  - provider: releases
    api_key:
      secure: fvBSa/8+JzFcWo+GGofbLDpcRbVNrmNjAJATJzq5Kr1RT8ngQ28Kn80OKr2wKid+A+gsJaEp2hXgXtDB/38YXecIwoBIEHSg+bCthBbd0UZIY6dTlrAeIkHbQ2LGU1nDWQRhj/IzeTI0mlAEph1nAWBSV2Tfux20G8Ijkp83re7Q8nCyNRr2TyxUouA8yY6O5fqzfzyNydvC9i7+ULH7whwKUXAT7Cy7hEZAPV2mNqYDhMXAM3v2Uld1LM7jh+oCzz4wa4cfVgx6ZZCPckNUiuIKCzWLO89fv6VumZmRAUIOtqaWqVyZJPbjhJ6OF4HmEiJMG7exFgRKhbcp6vCOc004VpSVrHaLkuCxkiT/N+68oXjqfFQ6wVBwoI2DHLRVekmUqhWWHouZDRvynU1wgAeQf27qnUIFcGl3/kIv8k39WFUWSxj6vrqJAIix32kCgjGaFKK8Y3C3YJ4hn84jgVk0fqQOeQQotPBhkP1j4WyB161kjeBt4u2PSYbwaSrDBPfhfQlWLuIEawQTVYT+SA9O7SRsAm48T6+uhT1dyivF4Dgl1d4Lahhlovq6eNu1mjX4pemA3ys6wv+aEySY/cbFVL6VeCL5qtJ+9eJoEQRyMH+uIUSZVZMDnmu2TqKJQtoue60sQRv1xBFbpC/VAwykViaxqN6lS0zXCEDiLBM=
    file_glob: true
    file:
      - target/*.pom
      - target/*.pom.asc
      - target/*.jar
      - target/*.jar.asc
    name: $PROJECT_VERSION
    skip_cleanup: true
    on:
      repo: hdensity/magnolia-configurable-version
      all_branches: true
      tags: true
